services:
  orphanage-frontend:
    image: orphanage-frontend
    container_name: orphanage-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - tibu-esb-network
    ports:
      - "8091:80"
    restart: unless-stopped


networks:
  tibu-esb-network:
    external: true
